name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read

env:
  BUNDLE_RETRY: 6
  BUNDLE_JOBS: 4

jobs:
  specs:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - 'jruby-10.0'
        include:
          - ruby: '3.4'
            coverage: 'true'
          - ruby: 'jruby-10.0'
            continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Start Kafka with Docker Compose
        run: |
          docker compose up -d || (sleep 5 && docker compose up -d)
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run all specs
        env:
          GITHUB_COVERAGE: ${{matrix.coverage}}
        continue-on-error: ${{ matrix.continue-on-error || false }}  # Use the matrix value if present
        run: |
          set -e
          bundle install --jobs 4 --retry 3
          cd ext && bundle exec rake
          cd ..
          bundle exec rspec

  specs_precompiled:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc \
            make \
            patch \
            tar \
            wget \
            ca-certificates
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: '3.4'
          bundler-cache: false
      - name: Build precompiled librdkafka.so
        run: |
          cd ext
          ./build-librdkafka-linux.sh
      - name: Install bundle with precompiled library
        env:
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        run: |
          # Install bundle dependencies (should use precompiled library)
          bundle install --jobs 4 --retry 3
          echo "Bundle install completed with precompiled library"
      - name: Start Kafka for precompiled tests
        run: |
          docker compose up -d || (sleep 5 && docker compose up -d)
      - name: Run specs with precompiled library
        run: |
          bundle exec rspec

  macos_build:
    timeout-minutes: 30
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - 'jruby-9.4'
        include:
          - ruby: 'jruby-10.0'
            continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: false
      - name: Build rdkafka-ruby
        continue-on-error: ${{ matrix.continue-on-error || false }}
        run: |
          set -e
          bundle install --jobs 4 --retry 3
          cd ext && bundle exec rake
