name: macOS CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read

env:
  BUNDLE_RETRY: 6
  BUNDLE_JOBS: 4

jobs:
  build_install:
    timeout-minutes: 30
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - 'jruby-9.4'
        include:
          - ruby: 'jruby-10.0'
            continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Bash 4+ and Kerberos
        run: |
          brew install bash krb5
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: false
      - name: Build rdkafka-ruby
        continue-on-error: ${{ matrix.continue-on-error || false }}
        run: |
          set -e
          bundle install --jobs 4 --retry 3
          cd ext && bundle exec rake

  build_precompiled:
    timeout-minutes: 45
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install Bash 4+ and Kerberos
        run: |
          brew install bash krb5
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Cache build-tmp directory
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ext/build-tmp
          key: build-tmp-${{ runner.os }}-${{ hashFiles('ext/*.sh', 'ext/Rakefile') }}-v2
      - name: Build precompiled librdkafka for macOS ARM64
        run: |
          cd ext
          /opt/homebrew/bin/bash ./build_macos_arm64.sh
      - name: Install bundle with precompiled library
        env:
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        run: |
          # Install bundle dependencies (should use precompiled library)
          bundle install --jobs 4 --retry 3
          echo "Bundle install completed with precompiled library"
